version: "3.9"
services:
  app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "phone-book"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
